version: "3"
services:
  pg-neptune:
    image: postgres:14.0-alpine
    networks:
      - neptune-ui
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=insightlab_db
    restart: unless-stopped

  neptune-ui:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - neptune-ui
    ports:
      # let Neptune-web use 3000 on host
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@pg-neptune:5432/insightlab_db
    restart: unless-stopped
    depends_on:
      - pg-neptune

networks:
  neptune-ui:
    driver: bridge
